### ISSUE TITLE
unwanted scrollbar on login page

### ISSUE THREAD

**Issue by sillevl** [vives-webapplications-2018/vue-project-weneedjesus#1]
On `/login` an unwanted horizontal scrollbar appears at the bottom of the page.

The scrollbar is caused by the `row` class. It adds margin on the left and right, expanding the element width beyond the screen viewport (screen) width, resulting in scrollbars.

2 ways of solving this issue:
* CSS way: set margin left and right to 0 pixels. This cannot be set globally with a class selector because this behaviour might introduce bugs or unwanted results on other `.row` elements.
* Place all page content in a `div.container`. This will centralize the content, preventing the the margins form resulting in a scrollbar. This can be applied globally on every page. This is the preferred solution.

**Comment by JensVercruysse** [comment]
Bug resolved
