### ISSUE TITLE
Submit button in /register does not react to clicking.

### ISSUE THREAD

**Issue by JelleDBZ** [vives-webapplications-2018/vue-project-weneedjesus#3]
I thought at first my $_POST['submit'] had to change to $_POST['action'] . But this doesn't resolve my problem. Aidez-moi s'il te plaît.

**Comment by sillevl** [comment]
There is no `method` attribute set in the form element. The default method is `GET`  (see [https://www.w3.org/TR/html401/interact/forms.html#h-17.3](https://www.w3.org/TR/html401/interact/forms.html#h-17.3)) Therefore you never call the `POST /register` route...

**Comment by JelleDBZ** [comment]
I've added POST method, but apparently this doesn't resolve the problem.

**Comment by sillevl** [comment]
The button has to be defined _inside_ the form element otherwise it will use the form settings nor wil it send the corresponding form data.

**Comment by JelleDBZ** [comment]
Problem has been resolved, thank you.
